### ISSUE TITLE
Doesn't seem to work on 2021 16" MacBook Pro M1 running latest version of macOS (12.6.1)

### ISSUE THREAD

**Issue by hsdajr** [Kalaschnik/adobe-fonts-revealer#12]
Newly added font didn't appear to be downloading in the same location (or maybe a permissions/security issue, not sure); they don't appear in the terminal listing when I run the reveal.sh command. But the new font does appear in the Font menu of apps like TextEdit, so it's on the Mac somewhere. Works fine when I tried it on my 2014 15" MacBook Pro running the latest version of macOS Big Sur. (Filson Pro font.)

Did notice the following when I did a few dry runs:

otfinfo: .38495.otf: OTF data for ‘CFF’ out of range
.38495.otf	⮕	.otf

If this helps.

**Comment by kalaschnik** [comment]
Humn, that is weird... I hardcorded all the paths... Maybe Apple silicon uses other paths 🤔

**Comment by puyma** [comment]
Checked on a M1 mac with that specific font. Works fine. 

Maybe check your otfinfo installation. Or maybe the file is corrupted somehow.

**Comment by kalaschnik** [comment]
Thanks for your feedback @puyma.
