### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by Cellomaster87** [Kalaschnik/adobe-fonts-revealer#13]
I have followed the installation instruction, but then running 'sh reveal' returns the 'no such file or directory' error. Do I need to be in some specific place with 'cd'? I am on macOS 12.6.7, the Terminal is set to its default ZSH. Thank you

**Comment by scoopy115** [comment]
You need to use the cd command and point it to the adobe-fonts-revealer folder, that worked for me.

**Comment by 117-droid** [comment]
I also followed the instructions, and had the same problem. However, when I attempt to cd to adobe-fonts-revealer, no such file. Did I miss something in the instructions/is there a file I should have downloaded? I installed the lcdc-typetools already. Maybe connected to how when I go into livetype hidden folder from adobe, my .r/ folder is just empty. No hidden files, just empty. Even though I have tons of Adobe fonts in my apps.

**Comment by kalaschnik** [comment]
What is your error message?
