### ISSUE TITLE
Powershell port of this script

### ISSUE THREAD

**Issue by pawalan** [Kalaschnik/adobe-fonts-revealer#14]
Hi Steven,
this is really useful, but a bit awkward to use under Windows, so I made a PowerShell port of the script at https://github.com/pawalan/adobe-fonts-liberator - feel free to link, I linked to your project in my Readme, too.

Beste Grüße aus Neuseeland nach good old Germany,
Sven

**Comment by kalaschnik** [comment]
Hey Sven, thanks for this! I never had the time to look into a Windows solution. I am very happy to link to your Windows solution!

Grüße aus Leipzig.
