### ISSUE TITLE
WSL reports "reveal: 6: do unexpected

### ISSUE THREAD

**Issue by josemunizdev** [Kalaschnik/adobe-fonts-revealer#20]
For WSL, the commands to make the sh file work are as follows:
`chmod +x reveal`
`./reveal`
Else it doesn't work with the instructions provided.

**Comment by kalaschnik** [comment]
Running `sh reveal` actually does not need an execute flag in chmod, since the shebang is set. If you just want to run the file with `./reveal` you indeed need the x flag
