### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by kalaschnik** [Kalaschnik/adobe-fonts-revealer#3]

**Comment by kalaschnik** [comment]
Use direct binaries to avoid dependencies:
https://ctan.mirror.norbert-ruehl.de/systems/win32/w32tex/lcdf-typetools-w32.tar.xz

**Comment by kalaschnik** [comment]
otfinfo is what I need for windows:
https://www.autohotkey.com/boards/viewtopic.php?t=824

**Comment by bukkadev** [comment]
Just wanted to add for others on Windows (WLS)

On windows the files are hidden by default so edit the script to check for files that start with a dot

I changed line 17 to:
`for file in * .[^.]*`

And also make sure to change the output/read directories on Windows: 
`C:\Users\*USER*\AppData\Roaming\Adobe\CoreSync\plugins\livetype\r`

Oh and also to run the script you have to use `bash reveal.sh` not `sh reveal.sh`

**Comment by SolHensnet** [comment]
Hey, So I am trying to change the output/read directories on Windows but I am having no luck and no matter what I try, the code always fails and I'm left scratching my head. Could anyone please help me? It doesn't help that I am very new to coding and am probably doing everything wrong. 
Thank you!

**Comment by kalaschnik** [comment]
I started working on the Windows version without the need of WSL and shipping it with otfinfo. This will be done in August.

**Comment by bennyboer** [comment]
> Hey, So I am trying to change the output/read directories on Windows but I am having no luck and no matter what I try, the code always fails and I'm left scratching my head. Could anyone please help me? It doesn't help that I am very new to coding and am probably doing everything wrong. Thank you!

Hi there, had the same problem so I've built a quick Rust command line tool that works for Windows (probably also other operating systems): https://github.com/bennyboer/adobe-font-grabber

**Comment by kalaschnik** [comment]
Native Powershell solution is here: https://github.com/pawalan/adobe-fonts-liberator
