### ISSUE TITLE
Syntax error near unexpected token 'newline'

### ISSUE THREAD

**Issue by jeremysexton** [Kalaschnik/adobe-fonts-revealer#4]
Just found this tool and downloaded it, installed lcdf-typetools with Homebrew and every time I attempted to run reveal.sh, it gives me the same 2 errors.

```bash
reveal.sh: line 7: syntax error near unexpected token `newline'
reveal.sh: line 7: `<!DOCTYPE html>'
```

Is this a new issue? Is it something wrong on my end? I'm using an M1 MBP running 11.3.

**Comment by kalaschnik** [comment]
Check Line 7:
https://github.com/Kalaschnik/adobe-fonts-revealer/blob/main/reveal.sh#L7
The scrip has no HTML content. You must run something different, but not that file. 

You should run this: `sh reveal.sh`

**Comment by jeremysexton** [comment]
Strange. I have been running `sh reveal.sh`

**Comment by jeremysexton** [comment]
Somehow when I downloaded it, it didn't grab the file. Not sure what happened, but it's not an issue with the script.
