### ISSUE TITLE
Can't find FONTS Folder inside Downloads directory.

### ISSUE THREAD

**Issue by suraj235** [Kalaschnik/adobe-fonts-revealer#6]
Hii,

I followed both steps on my mac. In step 2 `sh reveal` runs without any error with a message (see below).

>  DONE! Check your 'FONTS' directory within Downloads if you selected Option 2 (Copy).

But can't find any FONTS folder within Downloads. Is anything else I need to take care of?
P.S: I have selected option 2.

Thanks,

**Comment by kalaschnik** [comment]
But there are indeed fonts located in: `$HOME/Library/Application\ Support/Adobe/CoreSync/plugins/livetype/.r/`?

**Comment by suraj235** [comment]
> But there are indeed fonts located in: `$HOME/Library/Application\ Support/Adobe/CoreSync/plugins/livetype/.r/`?

Yes there are.

**Comment by kalaschnik** [comment]
On which macOS version are you? I wrote that under Catalina, and I'm still on Catalina. Maybe also try running the command with sudo?
