### ISSUE TITLE
WSL Reports unexpected "do"

### ISSUE THREAD

**Issue by Avieasolia** [Kalaschnik/adobe-fonts-revealer#7]
reveal.sh: 6: Syntax error: "do" unexpected

**Comment by kalaschnik** [comment]
On which macOS version are you? I wrote that under Catalina, and I'm still on Catalina. Maybe also try running the command with sudo?

**Comment by Avieasolia** [comment]
Maybe it was to do with me trying to run it on Windows, wasn't sure if it would still not work with windows. I have little familiarity with Bash but I ended up writing up a C# app to do the trick for windows users.
